# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swe599' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swe599

  pod 'Alamofire', '~> 4.8.1'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'Socket.IO-Client-Swift', '~> 15.0.0'

end
